# ****************************************************************************
# * Licensed Materials - Property of IBM
# * IBM Cloud Kubernetes Service, 5737-D43
# * (C) Copyright IBM Corp. 2021 All Rights Reserved.
# * US Government Users Restricted Rights - Use, duplication or
# * disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# ****************************************************************************

version: 1

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofumpt
    - revive
    - errcheck
    - ineffassign
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - rangeExprCopy
      - ifElseChain
      - appendCombine

  revive:
    severity: warning

  errcheck:
    check-blank: true

  gofumpt:
    extra-rules: true