language: go

go:
- "1.23.8"
- tip
group: bluezone

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

cache:
  bundler: true

sudo: true

before_install:
- sudo apt-get install bc

before_script:
- make deps
- go install github.com/pierrre/gotestcover

script:
- mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
- mkdir -p $GOPATH/src/github.com/IBM/ibm-vpc-file-csi-driver
- rsync -az . $GOPATH/src/github.com/IBM/ibm-vpc-file-csi-driver

- make fmt
- make test-sanity
- travis_wait 300 make test
- make coverage && touch "Passing" || touch "Failed"
- make driver

after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GHE_TOKEN}:@github.com" > .git/credentials
- "./scripts/calculateCoverage.sh"
- "./scripts/publishCoverage.sh"

after_failure:
- "./scripts/handleFailure.sh"
