kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-file-node-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v1.0.0
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.11.1
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v2.13.1
