kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-file-node-driver
          imagePullPolicy: Always
          image: registry.stage1.ng.bluemix.net/armada-master/ibm-vpc-file-csi-driver:latest
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
        - name: storage-secret-sidecar
          image: icr.io/obs/armada-storage-secret:v1.0.0
