---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1-pvc-validate
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-file-share-dp2
