---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-pvc-pod-validate
  labels:
    app: test1-pvc-pod-validate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1-pvc-pod-validate
  template:
    metadata:
      labels:
        app: test1-pvc-pod-validate
    spec:
      containers:
        - name: test1-pvc-pod-validate-container  # Container name inside of Pod
          image: rabbitmq  # Container Image name available within cluster
          volumeMounts:
            - mountPath: /myvol  # Container Mount Path for PVC
              name: test1-pvc-pod-validate-volume  # PVC name for this Pod
      volumes:
        - name: test1-pvc-pod-validate-volume  # Volume name in this Pod
          persistentVolumeClaim:
            claimName: test1-pvc-validate  # PVC name
