apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: <KUSTOMIZE> # DoNotEdit. Taken from kustomization.yaml
data:
  # Obtain Cluster ID using oc get nodes -l node-role.kubernetes.io/master --output json | jq -r '.items[0].metadata.name'
  # Obtain IBM Cloud Account ID using ibmcloud account show -o json | jq -r .account_id
  cluster-config.json: |
    {
      "cluster_id": "<UPDATE THIS>",
      "account_id": "<UPDATE THIS>"
    }
