apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
  namespace: <KUSTOMIZE>
data:
  cluster-config.json: |
    {
      "cluster_id": "<GIVE CLUSTER_ID>",
      "account_id": "<GIVE ACCOUNT ID>"
    }
