---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
  namespace: <KUSTOMIZE> # DoNotEdit. Taken from kustomization.yaml
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.2.0
          imagePullPolicy: IfNotPresent
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.15.0
          imagePullPolicy: IfNotPresent
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.13.2
          imagePullPolicy: IfNotPresent
        - name: iks-vpc-file-driver
          image: <UPDATE THIS> # Custom image built or use the images available from tags created https://cloud.ibm.com/docs/containers?topic=containers-cl-add-ons-vpc-file-csi-driver
          imagePullPolicy: Always
