apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-vpc-file-node-sa
  namespace: <KUSTOMIZE>
imagePullSecrets:
  - name: <UPDATE THIS> # Custom image pull secret created for the node service account