apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpc-file-eit
  labels:
    app.kubernetes.io/name: ibm-vpc-file-csi-driver
provisioner: vpc.file.csi.ibm.io
parameters:
  profile: "dp2"   # The VPC Storage profile used. https://cloud.ibm.com/docs/vpc?topic=vpc-file-storage-profiles.
  billingType: "hourly"  # The default billing policy used. The uer can override this default.
  iops: "1000"    # All PVC will get this fixed iops provisioned by using this storageclass.
  encrypted: "false"     # By default, encryption is managed by cloud provider. User can override this default.
  encryptionKey: ""      # If encrypted is true, then a user must specify the CRK-CRN.
  resourceGroup: ""      # By default resource group will be used from storage-secrete-store secret, User can override.
  isENIEnabled: "true"   # VPC File Share ENI/VNI feature will be used by all PVCs created with this storage class.
  isEITEnabled: "true"   # VPC File Share will have EIT enabled.
  securityGroupIDs: ""   # By default cluster security group i.e kube-<clusterID> will be used. User can provide their own command separated SGs.
  subnetID: ""    # User can provide subnetID in which the ENI/VNI will be created. Zone and region are mandatory for this. If not provided CSI driver will use the subnetID available in the cluster' VPC zone.
  region: ""             # By VPC CSI driver will select a region from cluster node's topology. The user can override this default.
  zone: "" # By VPC CSI driver will select a region from cluster node's topology. The user can override this default.
  primaryIPID: "" # Existing ID of reserved IP from the same subnet as the file share zone. Zone and region are mandatory for this. SubnetID is not mandatory for this.
  primaryIPAddress: "" # IPAddress for ENI/VNI to be created in the respective subnet of the zone. Zone, region and subnetID are mandatory for this.
  tags: ""             # User can add a list of tags "a, b, c" that will be used at the time of provisioning file share, by default CSI driver has its own tags.
  uid: "0"             # The initial user identifier for the file share, by default its root.
  gid: "0"             # The initial group identifier for the file share, by default its root.
  classVersion: "1"
reclaimPolicy: "Delete"
allowVolumeExpansion: true
