kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.2
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-attacher:v1.11.2
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.13.1
        - name: iks-vpc-file-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v1.0.0
