kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-file-node-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v3.0.4
        - name: csi-driver-registrar
          image: icr.io/ext/k8scsi/csi-node-driver-registrar:v1.2.0
          imagePullPolicy: IfNotPresent
        - name: liveness-probe
          image: quay.io/k8scsi/livenessprobe:v1.1.0
          imagePullPolicy: IfNotPresent
