apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-share-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-file-dp2
