apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpodrwm
  labels:
    app: testpodrwm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testpodrwm
  template:
    metadata:
      labels:
        app: testpodrwm
    spec:
      containers:
      - image: rabbitmq #image name which should be avilable within cluster
        name: rabbitmq # name of the container inside POD
        volumeMounts:
        - mountPath: /myfileshare  # mount path for pvc from container
          name: test-pvc # pvc name for this pod
      volumes:
      - name: test-pvc  # volume resource name in this POD, user can choose any name as per kubernetes
        persistentVolumeClaim:
          claimName: file-share-pvc # pvc name which was created by using claim.yaml file
