apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-tags-secret
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: example-storageclass-secret
