---
kind: CSIDriver
apiVersion: storage.k8s.io/v1
metadata:
  name: vpc.file.csi.ibm.io
  namespace: default
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
