---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ibm-vpc-file-csi-driver
namespace:
  kube-system
resources:
- config-map.yaml
- node-server.yaml
- controller-server.yaml
- setup-vpc-file-sa.yaml
- csidriver.yaml
