apiVersion: v1
kind: ConfigMap
metadata:
  name: ibm-vpc-file-csi-configmap
  namespace: kube-system
data:
  SECRET_CONFIG_PATH: "/etc/storage_ibmc"
  CSI_ENDPOINT: "unix:/csi/csi-vpc-file.sock"
  VPC_ENABLED: "True"
  VPC_VOLUME_TYPE: "vpc-share"
  VPC_API_TIMEOUT: "90s" # 1.5 minutes for API time out its not related with retry
  VPC_RETRY_ATTEMPT: "10" # Number of retry, overall time should not increase from k8s retry
  VPC_RETRY_INTERVAL: "60" # This is max retry Gap in seconds even considering for exponential retry
  VPC_API_VERSION: "2021-04-20"
  VPC_API_GENERATION: "1"
  VPC_ID: "r006-7491f5ef-0194-455e-a5e1-1b1fef5d647b"