---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: ibm-vpc-file-csi-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-vpc-file-csi-controller
      app.kubernetes.io/name: ibm-vpc-file-csi-driver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: ibm-vpc-file-csi-controller
        app.kubernetes.io/name: ibm-vpc-file-csi-driver
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: ibm-vpc-file-controller-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 2121
        runAsGroup: 2121
      containers:
        - name: csi-provisioner
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ADDRESS)"
            - "--timeout=600s"
            - "--feature-gates=Topology=true"
          env:
            - name: CSI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key:  CSI_ADDRESS
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=600s"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi-vpc-file.sock
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: iks-vpc-file-driver
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--lock_enabled=false"
            - "--sidecarEndpoint=$(SIDECAR_ADDRESS)"
          envFrom:
          - configMapRef:
              name: ibm-vpc-file-csi-configmap
          env:
            - name: CSI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key:  CSI_ENDPOINT
            - name: SIDECAR_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key: SIDECAR_ADDRESS
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: VPC_ID
              valueFrom:
                configMapKeyRef:
                  name: ibm-cloud-provider-data
                  key: vpc_id
            - name: VPC_SUBNET_IDS
              valueFrom:
                configMapKeyRef:
                  name: ibm-cloud-provider-data
                  key: vpc_subnet_ids
                  optional: true
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: customer-auth
              readOnly: true
              mountPath: /etc/storage_ibmc
            - name: cluster-info
              readOnly: true
              mountPath: /etc/storage_ibmc/cluster_info
            - name: socket-dir
              mountPath: /sidecardir
            - mountPath: /var/run/secrets/tokens
              name: vault-token
        - name: liveness-probe
          image: MUSTPATCHWITHKUSTOMIZE
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          args:
            - "--csi-address=$(CSI_ADDRESS)"
          env:
            - name: CSI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key:  CSI_ADDRESS
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 10Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: storage-secret-sidecar
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          args:
            - "--endpoint=$(SIDECAR_ENDPOINT)"
          env:
            - name: SIDECAR_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key: SIDECAR_ENDPOINT
          resources:
            limits:
              cpu: 12m
              memory: 20Mi
            requests:
              cpu: 3m
              memory: 5Mi
          volumeMounts:
            - mountPath: /sidecardir
              name: socket-dir
            - mountPath: /etc/storage_ibmc
              name: customer-auth
              readOnly: true
            - mountPath: /var/run/secrets/tokens
              name: vault-token
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: customer-auth
          secret:
            secretName: storage-secret-store
        - name: cluster-info
          configMap:
            name: cluster-info
        - name: vault-token
          projected:
            sources:
            - serviceAccountToken:
                path: vault-token
                expirationSeconds: 600
