kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-node
  labels:
    app.kubernetes.io/name: ibm-vpc-file-csi-driver
spec:
  selector:
    matchLabels:
      app: ibm-vpc-file-csi-node
      app.kubernetes.io/name: ibm-vpc-file-csi-driver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: ibm-vpc-file-csi-node
        app.kubernetes.io/name: ibm-vpc-file-csi-driver
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: ibm-vpc-file-node-sa
      tolerations:
      - operator: Exists
      containers:
        - name: csi-driver-registrar
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: false
          args:
            - "--v=5"
            - "--csi-address=$(CSI_ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REGISTRATION_SOCK)"
          env:
            - name: CSI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key:  CSI_ADDRESS
            - name: DRIVER_REGISTRATION_SOCK
              value: /var/lib/kubelet/plugins/vpc.file.csi.ibm.io/csi-vpc-file.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: iks-vpc-file-node-driver
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--sidecarEndpoint=$(SIDECAR_ADDRESS)"
          envFrom:
          - configMapRef:
              name: ibm-vpc-file-csi-configmap
          env:
            - name: CSI_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key: CSI_ENDPOINT
            - name: SIDECAR_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key: SIDECAR_ADDRESS
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SOCKET_PATH
              value: "/var/lib/ibmshare.sock"
            - name: IS_NODE_SERVER
              value: "true"
            - name: SIDECAR_GROUP_ID
              value: "2121"
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 20m
              memory: 50Mi
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: secret-sidecar-sock-dir
              mountPath: /sidecardir
            - name: kubelet-data-dir
              mountPath: /var/data/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
            - name: device-dir
              mountPath: /dev
            - name: etcudevpath
              mountPath: /etc/udev
            - name: runudevpath
              mountPath: /run/udev
            - name: libudevpath
              mountPath: /lib/udev
            - name : syspath
              mountPath: /sys
            - name: customer-auth
              readOnly: true
              mountPath: /etc/storage_ibmc
            - name: cluster-info
              readOnly: true
              mountPath: /etc/storage_ibmc/cluster_info
            - mountPath: /var/lib
              name: libpath
            - mountPath: /tmp/mount-helper
              name: mh-logs
        - name: liveness-probe
          securityContext:
            runAsNonRoot: true
            runAsUser: 2121
            runAsGroup: 2121
            privileged: false
            seLinuxOptions: # seLinux label is set as a precaution for accessing csi socket
              type: spc_t
              level: s0
          image: MUSTPATCHWITHKUSTOMIZE
          args:
            - "--csi-address=$(CSI_ADDRESS)"
          env:
            - name: CSI_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key:  CSI_ADDRESS
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 10Mi
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
        - name: storage-secret-sidecar
          securityContext:
            runAsNonRoot: true
            runAsUser: 2121
            runAsGroup: 2121
            privileged: false
          image: MUSTPATCHWITHKUSTOMIZE
          imagePullPolicy: Always
          args:
            - "--endpoint=$(SIDECAR_ENDPOINT)"
          env:
            - name: SIDECAR_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: ibm-vpc-file-csi-configmap
                  key: SIDECAR_ENDPOINT
          volumeMounts:
            - mountPath: /sidecardir
              name: secret-sidecar-sock-dir
            - mountPath: /var/run/secrets/tokens
              name: vault-token
      volumes:
        - name: secret-sidecar-sock-dir
          emptyDir: {}
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-data-dir
          hostPath:
            path: /var/data/kubelet # IKS worker
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/vpc.file.csi.ibm.io/
            type: DirectoryOrCreate
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: etcudevpath
          hostPath:
            path: /etc/udev
            type: Directory
        - name: runudevpath
          hostPath:
            path: /run/udev
            type: Directory
        - name: libudevpath
          hostPath:
            path: /lib/udev
            type: Directory
        - name: syspath
          hostPath:
            path: /sys
            type: Directory
        - name: customer-auth # altough its not required, This is just to finish lib configuration which is a common code in the driver
          secret:
            secretName: storage-secret-store
        - name: cluster-info # To get the cluster info
          configMap:
            name: cluster-info
        - name: vault-token
          projected:
            sources:
            - serviceAccountToken:
                path: vault-token
                expirationSeconds: 600
        - name: libpath
          hostPath:
            path: /var/lib
            type: Directory
        - name: mh-logs
          hostPath:
            path: /opt/ibm/mount-ibmshare/
