kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: icr.io/ext/sig-storage/csi-provisioner:v2.2.2
        - name: liveness-probe
          image: icr.io/ext/sig-storage/livenessprobe:v2.3.0
        - name: iks-vpc-file-driver
          imagePullPolicy: Always
          image: icr.io/obs/storage/ibm-vpc-file-csi-driver:v1.0.0-beta1
        - name: storage-secret-sidecar
          image: icr.io/obs/armada-storage-secret:v1.1.4
        - name: csi-resizer
          image: quay.io/k8scsi/csi-resizer:v1.2.0
