kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: icr.io/ext/sig-storage/csi-provisioner:v3.6.3
        - name: liveness-probe
          image: icr.io/ext/sig-storage/livenessprobe:v2.11.0
        - name: iks-vpc-file-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v1.1.5-beta
        - name: storage-secret-sidecar
          image: icr.io/obs/armada-storage-secret:v1.2.31
        - name: csi-resizer
          image: icr.io/ext/sig-storage/csi-resizer:v1.9.3