kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: icr.io/ext/k8scsi/csi-provisioner:v1.6.0
        - name: liveness-probe
          image: icr.io/ext/k8scsi/livenessprobe:v2.0.0
        - name: iks-vpc-file-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v3.0.4
