kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-controller
spec:
  template:
    spec:
      containers:
        - name: csi-provisioner
          image: icr.io/ext/sig-storage/csi-provisioner:v5.0.2
        - name: liveness-probe
          image: icr.io/ext/sig-storage/livenessprobe:v2.13.1
        - name: iks-vpc-file-driver
          imagePullPolicy: Always
          image: icr.io/ibm/ibm-vpc-file-csi-driver:v1.2.4-beta
        - name: storage-secret-sidecar
          image: icr.io/obs/armada-storage-secret:v1.2.31
        - name: csi-resizer
          image: icr.io/ext/sig-storage/csi-attacher:v1.11.2