kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ibm-vpc-file-csi-node
spec:
  template:
    spec:
      containers:
        - name: iks-vpc-file-node-driver
          imagePullPolicy: Always
          image: us.icr.io/sameshai/ibm-vpc-file-csi-driver:latest
        - name: csi-driver-registrar
          image: icr.io/ext/k8scsi/csi-node-driver-registrar:v1.2.0
        - name: liveness-probe
          image: icr.io/ext/k8scsi/livenessprobe:v2.0.0
        - name: storage-secret-sidecar
          image: us.icr.io/sameshai/armada-storage-secret-sidecar:v1.0.0
