// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pkg/tunnel/proto/tunnel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelManager_EnsureTunnel_FullMethodName = "/tunnel.TunnelManager/EnsureTunnel"
	TunnelManager_RemoveTunnel_FullMethodName = "/tunnel.TunnelManager/RemoveTunnel"
	TunnelManager_GetTunnel_FullMethodName    = "/tunnel.TunnelManager/GetTunnel"
	TunnelManager_ListTunnels_FullMethodName  = "/tunnel.TunnelManager/ListTunnels"
	TunnelManager_Health_FullMethodName       = "/tunnel.TunnelManager/Health"
)

// TunnelManagerClient is the client API for TunnelManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelManager service manages stunnel processes for RFS encryption in transit
type TunnelManagerClient interface {
	// EnsureTunnel creates a new tunnel or increments refcount if it exists
	EnsureTunnel(ctx context.Context, in *EnsureTunnelRequest, opts ...grpc.CallOption) (*EnsureTunnelResponse, error)
	// RemoveTunnel decrements refcount and removes tunnel if refcount reaches zero
	RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error)
	// GetTunnel retrieves information about a specific tunnel
	GetTunnel(ctx context.Context, in *GetTunnelRequest, opts ...grpc.CallOption) (*GetTunnelResponse, error)
	// ListTunnels returns all active tunnels
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	// Health checks the health of the tunnel manager service
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type tunnelManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelManagerClient(cc grpc.ClientConnInterface) TunnelManagerClient {
	return &tunnelManagerClient{cc}
}

func (c *tunnelManagerClient) EnsureTunnel(ctx context.Context, in *EnsureTunnelRequest, opts ...grpc.CallOption) (*EnsureTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureTunnelResponse)
	err := c.cc.Invoke(ctx, TunnelManager_EnsureTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelManagerClient) RemoveTunnel(ctx context.Context, in *RemoveTunnelRequest, opts ...grpc.CallOption) (*RemoveTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTunnelResponse)
	err := c.cc.Invoke(ctx, TunnelManager_RemoveTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelManagerClient) GetTunnel(ctx context.Context, in *GetTunnelRequest, opts ...grpc.CallOption) (*GetTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTunnelResponse)
	err := c.cc.Invoke(ctx, TunnelManager_GetTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelManagerClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, TunnelManager_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tunnelManagerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TunnelManager_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TunnelManagerServer is the server API for TunnelManager service.
// All implementations must embed UnimplementedTunnelManagerServer
// for forward compatibility.
//
// TunnelManager service manages stunnel processes for RFS encryption in transit
type TunnelManagerServer interface {
	// EnsureTunnel creates a new tunnel or increments refcount if it exists
	EnsureTunnel(context.Context, *EnsureTunnelRequest) (*EnsureTunnelResponse, error)
	// RemoveTunnel decrements refcount and removes tunnel if refcount reaches zero
	RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error)
	// GetTunnel retrieves information about a specific tunnel
	GetTunnel(context.Context, *GetTunnelRequest) (*GetTunnelResponse, error)
	// ListTunnels returns all active tunnels
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	// Health checks the health of the tunnel manager service
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedTunnelManagerServer()
}

// UnimplementedTunnelManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelManagerServer struct{}

func (UnimplementedTunnelManagerServer) EnsureTunnel(context.Context, *EnsureTunnelRequest) (*EnsureTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureTunnel not implemented")
}
func (UnimplementedTunnelManagerServer) RemoveTunnel(context.Context, *RemoveTunnelRequest) (*RemoveTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTunnel not implemented")
}
func (UnimplementedTunnelManagerServer) GetTunnel(context.Context, *GetTunnelRequest) (*GetTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTunnel not implemented")
}
func (UnimplementedTunnelManagerServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedTunnelManagerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedTunnelManagerServer) mustEmbedUnimplementedTunnelManagerServer() {}
func (UnimplementedTunnelManagerServer) testEmbeddedByValue()                       {}

// UnsafeTunnelManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelManagerServer will
// result in compilation errors.
type UnsafeTunnelManagerServer interface {
	mustEmbedUnimplementedTunnelManagerServer()
}

func RegisterTunnelManagerServer(s grpc.ServiceRegistrar, srv TunnelManagerServer) {
	// If the following call panics, it indicates UnimplementedTunnelManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelManager_ServiceDesc, srv)
}

func _TunnelManager_EnsureTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelManagerServer).EnsureTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelManager_EnsureTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelManagerServer).EnsureTunnel(ctx, req.(*EnsureTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelManager_RemoveTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelManagerServer).RemoveTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelManager_RemoveTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelManagerServer).RemoveTunnel(ctx, req.(*RemoveTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelManager_GetTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelManagerServer).GetTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelManager_GetTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelManagerServer).GetTunnel(ctx, req.(*GetTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelManager_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelManagerServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelManager_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelManagerServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TunnelManager_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TunnelManagerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TunnelManager_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TunnelManagerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TunnelManager_ServiceDesc is the grpc.ServiceDesc for TunnelManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelManager",
	HandlerType: (*TunnelManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureTunnel",
			Handler:    _TunnelManager_EnsureTunnel_Handler,
		},
		{
			MethodName: "RemoveTunnel",
			Handler:    _TunnelManager_RemoveTunnel_Handler,
		},
		{
			MethodName: "GetTunnel",
			Handler:    _TunnelManager_GetTunnel_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _TunnelManager_ListTunnels_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _TunnelManager_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/tunnel/proto/tunnel.proto",
}
