// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/tunnel/proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus represents the health state of the service
type HealthStatus int32

const (
	HealthStatus_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTHY   HealthStatus = 1
	HealthStatus_UNHEALTHY HealthStatus = 2
	HealthStatus_DEGRADED  HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "DEGRADED",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"DEGRADED":  3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_tunnel_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_pkg_tunnel_proto_tunnel_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

// EnsureTunnelRequest contains parameters for creating or reusing a tunnel
type EnsureTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volumeID is the unique identifier for the NFS share
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// nfs_server is the IP address of the NFS server
	NfsServer     string `protobuf:"bytes,2,opt,name=nfs_server,json=nfsServer,proto3" json:"nfs_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTunnelRequest) Reset() {
	*x = EnsureTunnelRequest{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTunnelRequest) ProtoMessage() {}

func (x *EnsureTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTunnelRequest.ProtoReflect.Descriptor instead.
func (*EnsureTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *EnsureTunnelRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *EnsureTunnelRequest) GetNfsServer() string {
	if x != nil {
		return x.NfsServer
	}
	return ""
}

// EnsureTunnelResponse returns information about the ensured tunnel
type EnsureTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel contains the tunnel information
	Tunnel *TunnelInfo `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	// created indicates if a new tunnel was created (true) or reused (false)
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureTunnelResponse) Reset() {
	*x = EnsureTunnelResponse{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureTunnelResponse) ProtoMessage() {}

func (x *EnsureTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureTunnelResponse.ProtoReflect.Descriptor instead.
func (*EnsureTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *EnsureTunnelResponse) GetTunnel() *TunnelInfo {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *EnsureTunnelResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// RemoveTunnelRequest contains parameters for removing a tunnel
type RemoveTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the unique identifier for the NFS share
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelRequest) Reset() {
	*x = RemoveTunnelRequest{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelRequest) ProtoMessage() {}

func (x *RemoveTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelRequest.ProtoReflect.Descriptor instead.
func (*RemoveTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveTunnelRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

// RemoveTunnelResponse indicates the result of tunnel removal
type RemoveTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// removed indicates if the tunnel was completely removed (true) or just decremented (false)
	Removed bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	// ref_count is the remaining reference count after removal
	RefCount      int32 `protobuf:"varint,2,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTunnelResponse) Reset() {
	*x = RemoveTunnelResponse{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTunnelResponse) ProtoMessage() {}

func (x *RemoveTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTunnelResponse.ProtoReflect.Descriptor instead.
func (*RemoveTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveTunnelResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

func (x *RemoveTunnelResponse) GetRefCount() int32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

// GetTunnelRequest contains parameters for retrieving tunnel information
type GetTunnelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the unique identifier for the NFS share
	VolumeId      string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelRequest) Reset() {
	*x = GetTunnelRequest{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRequest) ProtoMessage() {}

func (x *GetTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *GetTunnelRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

// GetTunnelResponse returns tunnel information
type GetTunnelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnel contains the tunnel information
	Tunnel *TunnelInfo `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	// found indicates if the tunnel was found
	Found         bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelResponse) Reset() {
	*x = GetTunnelResponse{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelResponse) ProtoMessage() {}

func (x *GetTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *GetTunnelResponse) GetTunnel() *TunnelInfo {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *GetTunnelResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// ListTunnelsRequest is empty as it lists all tunnels
type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{6}
}

// ListTunnelsResponse returns all active tunnels
type ListTunnelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tunnels is the list of all active tunnels
	Tunnels []*TunnelInfo `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	// total_count is the total number of tunnels
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

func (x *ListTunnelsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// HealthRequest checks service health
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{8}
}

// HealthResponse indicates service health status
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status indicates the health status
	Status HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=tunnel.HealthStatus" json:"status,omitempty"`
	// message provides additional health information
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// active_tunnels is the number of currently active tunnels
	ActiveTunnels int32 `protobuf:"varint,3,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	// failed_tunnels is the number of failed tunnels
	FailedTunnels int32 `protobuf:"varint,4,opt,name=failed_tunnels,json=failedTunnels,proto3" json:"failed_tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetActiveTunnels() int32 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *HealthResponse) GetFailedTunnels() int32 {
	if x != nil {
		return x.FailedTunnels
	}
	return 0
}

// TunnelInfo contains information about a tunnel
type TunnelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_id is the unique identifier for the NFS share
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	// remote_addr is the NFS server IP address
	RemoteAddr string `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// local_port is the local port the tunnel listens on
	LocalPort int32 `protobuf:"varint,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	// state is the current state of the tunnel
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// ref_count is the number of active mounts using this tunnel
	RefCount int32 `protobuf:"varint,5,opt,name=ref_count,json=refCount,proto3" json:"ref_count,omitempty"`
	// restart_count is the number of times the tunnel has been restarted
	RestartCount int32 `protobuf:"varint,6,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// last_healthy is the timestamp of the last successful health check (Unix timestamp)
	LastHealthy int64 `protobuf:"varint,7,opt,name=last_healthy,json=lastHealthy,proto3" json:"last_healthy,omitempty"`
	// config_path is the path to the stunnel configuration file
	ConfigPath    string `protobuf:"bytes,8,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_tunnel_proto_tunnel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP(), []int{10}
}

func (x *TunnelInfo) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *TunnelInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *TunnelInfo) GetLocalPort() int32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *TunnelInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TunnelInfo) GetRefCount() int32 {
	if x != nil {
		return x.RefCount
	}
	return 0
}

func (x *TunnelInfo) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *TunnelInfo) GetLastHealthy() int64 {
	if x != nil {
		return x.LastHealthy
	}
	return 0
}

func (x *TunnelInfo) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

var File_pkg_tunnel_proto_tunnel_proto protoreflect.FileDescriptor

const file_pkg_tunnel_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/tunnel/proto/tunnel.proto\x12\x06tunnel\"Q\n" +
	"\x13EnsureTunnelRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1d\n" +
	"\n" +
	"nfs_server\x18\x02 \x01(\tR\tnfsServer\"\\\n" +
	"\x14EnsureTunnelResponse\x12*\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x12.tunnel.TunnelInfoR\x06tunnel\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"2\n" +
	"\x13RemoveTunnelRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"M\n" +
	"\x14RemoveTunnelResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\x12\x1b\n" +
	"\tref_count\x18\x02 \x01(\x05R\brefCount\"/\n" +
	"\x10GetTunnelRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"U\n" +
	"\x11GetTunnelResponse\x12*\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x12.tunnel.TunnelInfoR\x06tunnel\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x14\n" +
	"\x12ListTunnelsRequest\"d\n" +
	"\x13ListTunnelsResponse\x12,\n" +
	"\atunnels\x18\x01 \x03(\v2\x12.tunnel.TunnelInfoR\atunnels\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x0f\n" +
	"\rHealthRequest\"\xa6\x01\n" +
	"\x0eHealthResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.tunnel.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eactive_tunnels\x18\x03 \x01(\x05R\ractiveTunnels\x12%\n" +
	"\x0efailed_tunnels\x18\x04 \x01(\x05R\rfailedTunnels\"\x85\x02\n" +
	"\n" +
	"TunnelInfo\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x12\x1d\n" +
	"\n" +
	"local_port\x18\x03 \x01(\x05R\tlocalPort\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1b\n" +
	"\tref_count\x18\x05 \x01(\x05R\brefCount\x12#\n" +
	"\rrestart_count\x18\x06 \x01(\x05R\frestartCount\x12!\n" +
	"\flast_healthy\x18\a \x01(\x03R\vlastHealthy\x12\x1f\n" +
	"\vconfig_path\x18\b \x01(\tR\n" +
	"configPath*E\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\f\n" +
	"\bDEGRADED\x10\x032\xe8\x02\n" +
	"\rTunnelManager\x12I\n" +
	"\fEnsureTunnel\x12\x1b.tunnel.EnsureTunnelRequest\x1a\x1c.tunnel.EnsureTunnelResponse\x12I\n" +
	"\fRemoveTunnel\x12\x1b.tunnel.RemoveTunnelRequest\x1a\x1c.tunnel.RemoveTunnelResponse\x12@\n" +
	"\tGetTunnel\x12\x18.tunnel.GetTunnelRequest\x1a\x19.tunnel.GetTunnelResponse\x12F\n" +
	"\vListTunnels\x12\x1a.tunnel.ListTunnelsRequest\x1a\x1b.tunnel.ListTunnelsResponse\x127\n" +
	"\x06Health\x12\x15.tunnel.HealthRequest\x1a\x16.tunnel.HealthResponseB9Z7github.com/IBM/ibm-vpc-file-csi-driver/pkg/tunnel/protob\x06proto3"

var (
	file_pkg_tunnel_proto_tunnel_proto_rawDescOnce sync.Once
	file_pkg_tunnel_proto_tunnel_proto_rawDescData []byte
)

func file_pkg_tunnel_proto_tunnel_proto_rawDescGZIP() []byte {
	file_pkg_tunnel_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_pkg_tunnel_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_tunnel_proto_tunnel_proto_rawDesc), len(file_pkg_tunnel_proto_tunnel_proto_rawDesc)))
	})
	return file_pkg_tunnel_proto_tunnel_proto_rawDescData
}

var file_pkg_tunnel_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_tunnel_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_tunnel_proto_tunnel_proto_goTypes = []any{
	(HealthStatus)(0),            // 0: tunnel.HealthStatus
	(*EnsureTunnelRequest)(nil),  // 1: tunnel.EnsureTunnelRequest
	(*EnsureTunnelResponse)(nil), // 2: tunnel.EnsureTunnelResponse
	(*RemoveTunnelRequest)(nil),  // 3: tunnel.RemoveTunnelRequest
	(*RemoveTunnelResponse)(nil), // 4: tunnel.RemoveTunnelResponse
	(*GetTunnelRequest)(nil),     // 5: tunnel.GetTunnelRequest
	(*GetTunnelResponse)(nil),    // 6: tunnel.GetTunnelResponse
	(*ListTunnelsRequest)(nil),   // 7: tunnel.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),  // 8: tunnel.ListTunnelsResponse
	(*HealthRequest)(nil),        // 9: tunnel.HealthRequest
	(*HealthResponse)(nil),       // 10: tunnel.HealthResponse
	(*TunnelInfo)(nil),           // 11: tunnel.TunnelInfo
}
var file_pkg_tunnel_proto_tunnel_proto_depIdxs = []int32{
	11, // 0: tunnel.EnsureTunnelResponse.tunnel:type_name -> tunnel.TunnelInfo
	11, // 1: tunnel.GetTunnelResponse.tunnel:type_name -> tunnel.TunnelInfo
	11, // 2: tunnel.ListTunnelsResponse.tunnels:type_name -> tunnel.TunnelInfo
	0,  // 3: tunnel.HealthResponse.status:type_name -> tunnel.HealthStatus
	1,  // 4: tunnel.TunnelManager.EnsureTunnel:input_type -> tunnel.EnsureTunnelRequest
	3,  // 5: tunnel.TunnelManager.RemoveTunnel:input_type -> tunnel.RemoveTunnelRequest
	5,  // 6: tunnel.TunnelManager.GetTunnel:input_type -> tunnel.GetTunnelRequest
	7,  // 7: tunnel.TunnelManager.ListTunnels:input_type -> tunnel.ListTunnelsRequest
	9,  // 8: tunnel.TunnelManager.Health:input_type -> tunnel.HealthRequest
	2,  // 9: tunnel.TunnelManager.EnsureTunnel:output_type -> tunnel.EnsureTunnelResponse
	4,  // 10: tunnel.TunnelManager.RemoveTunnel:output_type -> tunnel.RemoveTunnelResponse
	6,  // 11: tunnel.TunnelManager.GetTunnel:output_type -> tunnel.GetTunnelResponse
	8,  // 12: tunnel.TunnelManager.ListTunnels:output_type -> tunnel.ListTunnelsResponse
	10, // 13: tunnel.TunnelManager.Health:output_type -> tunnel.HealthResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_tunnel_proto_tunnel_proto_init() }
func file_pkg_tunnel_proto_tunnel_proto_init() {
	if File_pkg_tunnel_proto_tunnel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_tunnel_proto_tunnel_proto_rawDesc), len(file_pkg_tunnel_proto_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_tunnel_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_pkg_tunnel_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_pkg_tunnel_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_pkg_tunnel_proto_tunnel_proto_msgTypes,
	}.Build()
	File_pkg_tunnel_proto_tunnel_proto = out.File
	file_pkg_tunnel_proto_tunnel_proto_goTypes = nil
	file_pkg_tunnel_proto_tunnel_proto_depIdxs = nil
}
