apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-retained-pvc
  namespace: default
spec:
  storageClassName: vpc-file-nfs-subdir-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
