apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-archived-pvc
  namespace: default
spec:
  storageClassName: vpc-file-nfs-subdir-archive
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
