apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-nfs-restored-pvc
  namespace: default
spec:
  storageClassName: vpc-file-nfs-subdir
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: my-nfs-snap-v1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
