apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-wffc-app
  namespace: default
  labels:
    app: nfs-wffc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-wffc-app
  template:
    metadata:
      labels:
        app: nfs-wffc-app
    spec:
      containers:
        - name: app
          image: nginx:stable-alpine
          volumeMounts:
            - name: data
              mountPath: /volume-mount/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: my-wffc-pvc
