---
# Kustomize v5.5.0 syntax
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manifests
labels:
- includeSelectors: true
  pairs:
    addonmanager.kubernetes.io/mode: Reconcile
commonAnnotations:
  version: (( grab $TRAVIS_COMMIT || "dev" ))
patches:
- path: controller-server-images.yaml
- path: node-server-images.yaml
