---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../manifests
commonLabels:
  addonmanager.kubernetes.io/mode: Reconcile
commonAnnotations:
  version: (( grab $TRAVIS_COMMIT || "dev" ))
patches:
- controller-server-images.yaml
- node-server-images.yaml
