apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-secret
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-file-dp-eni-custom