apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-file-pvc-good
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-file-5iops-tier
