apiVersion: apps/v1
kind: Deployment
metadata:
  name: testpodrwm
  labels:
    app: testpodrwm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testpodrwm
  template:
    metadata:
      labels:
        app: testpodrwm
    spec:
      containers:
      - image: rabbitmq #image name which should be avilable within cluster
        name: container-name # name of the container inside POD
        volumeMounts:
        - mountPath: /myvol  # mount path for pvc from container
          name: pvc-name # pvc name for this pod
      volumes:
      - name: pvc-name  # volume resource name in this POD, user can choose any name as per kubernetes
        persistentVolumeClaim:
          claimName: csi-file-pvc-good # pvc name which was created by using claim.yaml file
